#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  vars:
    # Install some ubuntu packages.
    ubuntu_packages:
      - bash
      - bash-completion
      - ca-certificates
      - curl
      - git
      - openssl
      - openssh-client
      - openssh-server
      - python3

    # Some python package dependencies.
    apt_python_packages:
      - python3-pip
      - libpng-dev
      - libjpeg8-dev
      - libfreetype6-dev
      - pkg-config
      - libxft-dev
      
    # Python Packages.
    pip_packages:
      - docker-py
      - docker-compose
      - numpy
      - matplotlib
      - scipy
      - pandas
      - pillow
      
    pip3_packages:
      - numpy
      - matplotlib
      - scipy
      - pillow
      - pandas

    jupyter_notebook_config_py_url: "https://raw.githubusercontent.com/hk1953/ucsl-image/master/image/jupyter_config.py"
    ansible_cfg_url: "https://raw.githubusercontent.com/hk1953/ucsl-image/master/image/ansible.cfg"
    inventory_url: "https://raw.githubusercontent.com/hk1953/ucsl-image/master/image/inventory"

  tasks:
    # General Ubuntu package installation.
    - name: install same packages
      package: name={{ item }} state=present
      with_items: "{{ ubuntu_packages }}"
      when:
        - ubuntu_packages is defined
        - ansible_pkg_mgr == "apt"

    # Python package dependencies
    - name: install apt packages
      apt: name={{ item }} state=present
      with_items: "{{ apt_packages }}"
      when:
        - apt_python_packages is defined
        - ansible_pkg_mgr == "apt"

    # Create a 2048-bit SSH key for root
    - name: create ssh key for root
      user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

    - name: Install requirements
      pip: 
        requirements: ./requirements.txt
        virtualenv: /home/venvs/myenv
        virtualenv_python: python3.4

    # install Jupyter.
    - name: upgrade the six
      pip: name=six state=latest

    - name: install jupyter notebook
      pip: name=jupyter version=5.0.0 state=present

    # Disable Jupyter token authentication (DO NOT RUN THIS IN PRODUCTION!)
    - name: create `/root/.jupyter` directory
      file: path=/root/.jupyter state=directory mode=0700

    - name: get the jupyter_notebook_config.py
      get_url: >
        url={{ jupyter_notebook_config_py_url }} dest=/root/.jupyter/jupyter_notebook_config.py mode=0644
        checksum=sha256:9b2f10934fa1a7476df334135021432fd73298a7eb472fd1194acbba8e7f8f90

    # Get the ansible.cfg.
    - name: get the ansible.cfg file
      get_url: >
        url={{ ansible_cfg_url }} dest=/home/ mode=0644 
        checksum=sha256:cc53d9e897e0f226c53aaa3b33a34c94e3fc812a7152c463188a43aad17d2955

    # Get the inventory file.
    - name: get the inventory file
      get_url: >
        url={{ inventory_url }} dest=/home/ mode=0644 
        checksum=sha256:4315236a3f6e432244effda39115fc51b26aacfba995fbc3e4eeb3da54e6840b
